const ADD_TO_STORE='ADD_TO_STORE';
const REMOVE_FROM_STORE='REMOVE_FROM_STORE';
const RESET_STORE_LIST='RESET_STORE_LIST';
const CHANGE_SORT='CHANGE_SORT';
const RESET_SORT='CHANGE_SORT'
const INCREASE_RENDER='INCREASE_RENDER'
export default{
    ADD_TO_STORE,
    REMOVE_FROM_STORE,
    RESET_STORE_LIST,
    CHANGE_SORT,
    RESET_SORT,
    INCREASE_RENDER,
}