const ADD_TO_STORE='ADD_TO_STORE';
const REMOVE_FROM_STORE='REMOVE_FROM_STORE';
const RESET_STORE_LIST='RESET_STORE_LIST';

export default{
    ADD_TO_STORE,
    REMOVE_FROM_STORE,
    RESET_STORE_LIST,
}