const INCREASE_IN_SHOPPING_CART='INCREASE_IN_SHOPPING_CART';
const DECREASE_IN_SHOPPING_CART='DECREASE_IN_SHOPPING_CART';
const REMOVE_FROM_SHOPPING_CART='REMOVE_FROM_SHOPPING_CART';
const RESET_SHOPPING_CART='RESET_SHOPPING_CART';
export default{
    INCREASE_IN_SHOPPING_CART,
    DECREASE_IN_SHOPPING_CART,
    REMOVE_FROM_SHOPPING_CART,
    RESET_SHOPPING_CART,
}